### ISSUE TITLE
Does not run on Android

### ISSUE THREAD

**Issue by thekiefs** [libretro/virtualjaguar-libretro#44]
I'm trying to get Virtual Jaguar to load any game on Android but have been unsuccessful. RetroArch just hangs and then quits.

Any ideas are appreciated.

**Comment by Testsr** [comment]
Can reproduce, except for Pinball game.

**Comment by Cee123** [comment]
I can get them to run. But as usual they run slow and glitchy with this emulator.

**Comment by thekiefs** [comment]
@Cee123 Can you share your Android specific setup please?

**Comment by Cee123** [comment]
@thekiefs Sure thing, last time I tested it was working. Can't say for sure it still works. But when it did work it ran like crap.

**Comment by Cee123** [comment]
It works on my Samsung Galaxy S7, running Android 8 on RetroArch 1.8.5.
It also works on my Q Box Android Box running Android 5.1.1 on RetroArch 1.8.5.
It also worked on my HTC 10 phone (my phone before this), running Android 8 on RetroArch 1.7.0.

BUT it's not even playable on any of those because of the horrendously slow speeds and awful graphical glitches.
