### ISSUE TITLE
[bug] Numpad 7, 8, 9, *, # input impossible for player 2 and above in RetroArch or P1 controllers.

### ISSUE THREAD

**Issue by VideogameScrapbook** [libretro/virtualjaguar-libretro#54]
This is related to this issue, but that one is specifically about joypad mapping:
https://github.com/libretro/virtualjaguar-libretro/issues/39

There's a workaround of using the keyboard number keys for player 1. But there is no such option for players 2 and above.

**Comment by JoeMatt** [comment]
They're mappable as as controller. This is odd I know, but I actually use this core with a different UI since I'm an iOS dev so my input mapping isn't 1:1 with retro arches but the code to read them is there,

https://github.com/libretro/virtualjaguar-libretro/blob/3fd8160628295f5a21188f28548895a9a8a8955a/libretro.c#L383

I'm not sure how retro-arch handles keyboard input for 2player games so that might be a limitation of the front-end?

There was another bug in the core itself for decoding input buffers, so I wasn't sure if that was related to this or if this is purely the inability to map the input through retroarch the way you require for keyboard. (it should work with 2  controllers though)

**Comment by JoeMatt** [comment]
Unfortunately I don't see a way to map the keys to a controller since the enums used internally for libretro.h stop after key_6 (r3).

I'm trying to find if other cores have a work around, since it's not the only system with a numbered input,
ColecoVision, Atari 5200

Though they both have less buttons overall since they only have 1 or 2 non numbered buttons.
